
```{r}
#| label: dimred_plots
#| fig-height: 6
#| results: 'asis'
component <-
  component_dimred_plots(
    pg_data_processed,
    plot_reductions = preferred_dimred_order(Reductions(pg_data_processed)),
    sample_palette = sample_palette,
    cluster_palette = cluster_palette,
    sample_plots = FALSE,
    plot_height = 6
  )

tabset_nested_plotlist(component, level = 3)
```

We run an automatic annotation using an annotated reference dataset. This allows
us to put a few simple labels on cell populations, which can be useful for 
downstream analysis. We visualize the annotation using UMAPs 
(integrated and not).

::: {.panel-tabset .nav-pills}

### Automated annotation

```{r}
#| label: annotation_dimred
#| results: 'asis'
component <-
  component_annotation(pg_data_processed,
    heatmap_gradient = cherry_gradient
  )

tabset_plotlist(component$dimred_plots, level = 4, close = FALSE)
```

#### Cluster heatmap

```{r}
#| label: annotation_dimred_heatmap
#| fig-height: 17
#| results: 'asis'
component$heatmap
```

:::

### Summary

```{r}
#| label: annotation_summary
#| fig-height: 4
#| results: 'asis'
component$celltype_composition
```


```{r}
#| label: annotation_summary2
#| fig-height: 4
#| results: 'asis'
tabset_plotlist(component$celltype_composition_barplots1, level = 4)
```


```{r}
#| label: annotation_summary3
#| fig-height: 4
#| results: 'asis'
tabset_plotlist(component$celltype_composition_barplots2, level = 4)
```


```{r}
#| label: annotation_summary4
#| fig-height: 4
#| results: 'asis'
component$celltype_composition_table
```

:::
