---
title: "EXPERIMENT SUMMARY REPORT"
subtitle: "v0.4.0" 
format:
  html:
    theme: default
    page-layout: full
    toc: true
    toc-location: left
    toc-depth: 4
    embed-resources: true
    code-folding: show
    fig-width: 8
    fig-height: 5
    fig-dpi: 96
    grid:
      body-width: 900px
    css: styles.css
knitr:
  opts_chunk:
    out.width: "100%"
date: "`r Sys.Date()`"
editor_options: 
  chunk_output_type: console
execute:
  dev: ragg_png
  execute-dir: dir
  echo: false
  warning: false
  message: false
params: 
  
  sample_sheet: "../../../ES_test_data/test_samplesheet.csv"
  data_folder: "../../../ES_test_data/"
  control_markers: ["mIgG1", "mIgG2a", "mIgG2b"]
  do_harmonize: FALSE
  harmonization_vars: ["condition"]
  norm_method: "CLR"
  clustering_resolution: 1
  annotation_method: "Seurat"
  mc_cores: 1
  debug_mode: FALSE
  test_mode: FALSE
---

```{r, child="preprocessing.qmd"}
```

# 

::: {.panel-tabset .nav-pills}
  
## Samples 

```{r}
#| label: samples
#| results: 'asis'
print_metadata_table(sample_sheet)
```

## Quality metrics

```{r, child="quality_metrics.qmd"}
```

## Cell annotation

```{r, child="cell_annotation.qmd"}
```

## Abundance 

```{r, child="abundance.qmd"}
```

## Spatial metrics

```{r, child="spatial.qmd"}
```

## Run settings

```{r}
#| label: run_settings
# Print parameters
print_params(params)

# Print session info
print_session_info()
```


:::
