#' @keywords internal
"_PACKAGE"

## usethis namespace: start
#' @importFrom cli cli_abort
#' @importFrom ComplexHeatmap pheatmap
#' @importFrom dplyr %>%
#' @importFrom dplyr across
#' @importFrom dplyr arrange
#' @importFrom dplyr bind_cols
#' @importFrom dplyr bind_rows
#' @importFrom dplyr case_when
#' @importFrom dplyr collect
#' @importFrom dplyr count
#' @importFrom dplyr desc
#' @importFrom dplyr distinct
#' @importFrom dplyr everything
#' @importFrom dplyr filter
#' @importFrom dplyr group_by
#' @importFrom dplyr group_by_all
#' @importFrom dplyr group_keys
#' @importFrom dplyr group_map
#' @importFrom dplyr group_split
#' @importFrom dplyr if_else
#' @importFrom dplyr inner_join
#' @importFrom dplyr join_by
#' @importFrom dplyr left_join
#' @importFrom dplyr mutate
#' @importFrom dplyr mutate_all
#' @importFrom dplyr n
#' @importFrom dplyr n_distinct
#' @importFrom dplyr pull
#' @importFrom dplyr reframe
#' @importFrom dplyr rename
#' @importFrom dplyr row_number
#' @importFrom dplyr rowwise
#' @importFrom dplyr select
#' @importFrom dplyr slice_head
#' @importFrom dplyr slice_sample
#' @importFrom dplyr summarise
#' @importFrom dplyr summarize
#' @importFrom dplyr top_n
#' @importFrom dplyr ungroup
#' @importFrom ggplot2 aes
#' @importFrom ggplot2 coord_equal
#' @importFrom ggplot2 coord_fixed
#' @importFrom ggplot2 element_blank
#' @importFrom ggplot2 element_line
#' @importFrom ggplot2 element_rect
#' @importFrom ggplot2 element_text
#' @importFrom ggplot2 expansion
#' @importFrom ggplot2 facet_grid
#' @importFrom ggplot2 facet_wrap
#' @importFrom ggplot2 geom_blank
#' @importFrom ggplot2 geom_col
#' @importFrom ggplot2 geom_hline
#' @importFrom ggplot2 geom_jitter
#' @importFrom ggplot2 geom_line
#' @importFrom ggplot2 geom_point
#' @importFrom ggplot2 geom_segment
#' @importFrom ggplot2 geom_text
#' @importFrom ggplot2 geom_tile
#' @importFrom ggplot2 geom_violin
#' @importFrom ggplot2 ggplot
#' @importFrom ggplot2 ggplot_build
#' @importFrom ggplot2 guide_legend
#' @importFrom ggplot2 guides
#' @importFrom ggplot2 labs
#' @importFrom ggplot2 position_dodge
#' @importFrom ggplot2 position_jitter
#' @importFrom ggplot2 position_stack
#' @importFrom ggplot2 scale_color_manual
#' @importFrom ggplot2 scale_fill_gradientn
#' @importFrom ggplot2 scale_fill_manual
#' @importFrom ggplot2 scale_x_continuous
#' @importFrom ggplot2 scale_x_discrete
#' @importFrom ggplot2 scale_x_log10
#' @importFrom ggplot2 scale_y_continuous
#' @importFrom ggplot2 scale_y_log10
#' @importFrom ggplot2 theme
#' @importFrom ggplot2 theme_bw
#' @importFrom ggplot2 theme_void
#' @importFrom ggplot2 waiver
#' @importFrom ggplotify as.ggplot
#' @importFrom grid unit
#' @importFrom harmony RunHarmony
#' @importFrom knitr kable
#' @importFrom methods as
#' @importFrom parallel mclapply
#' @importFrom pixelatorR AnnotateCells
#' @importFrom pixelatorR ColocalizationHeatmap
#' @importFrom pixelatorR Edgelists
#' @importFrom pixelatorR FilterProximityScores
#' @importFrom pixelatorR minimal_pna_pxl_file
#' @importFrom pixelatorR Pixelgen_accent_colors
#' @importFrom pixelatorR PixelgenAccentColors
#' @importFrom pixelatorR PredictDoublets
#' @importFrom pixelatorR ProximityScores
#' @importFrom pixelatorR ReadPNA_edgelist
#' @importFrom pixelatorR ReadPNA_Seurat
#' @importFrom pixelatorR sequencing_saturation
#' @importFrom pixelatorR SummarizeProximityScores
#' @importFrom purrr map
#' @importFrom purrr reduce
#' @importFrom RcppSimdJson fload
#' @importFrom readr col_character
#' @importFrom readr col_integer
#' @importFrom readr cols
#' @importFrom readr read_csv
#' @importFrom readr read_rds
#' @importFrom rlang :=
#' @importFrom rlang set_names
#' @importFrom rlang sym
#' @importFrom scales percent
#' @importFrom sessioninfo package_info
#' @importFrom Seurat FindClusters
#' @importFrom Seurat FindNeighbors
#' @importFrom Seurat NormalizeData
#' @importFrom Seurat RunPCA
#' @importFrom Seurat RunUMAP
#' @importFrom Seurat ScaleData
#' @importFrom SeuratObject AddMetaData
#' @importFrom SeuratObject CreateSeuratObject
#' @importFrom SeuratObject Embeddings
#' @importFrom SeuratObject FetchData
#' @importFrom SeuratObject JoinLayers
#' @importFrom SeuratObject LayerData
#' @importFrom SeuratObject Reductions
#' @importFrom stats as.formula
#' @importFrom stats lm
#' @importFrom stats mad
#' @importFrom stats median
#' @importFrom stats sd
#' @importFrom stats setNames
#' @importFrom stats weighted.mean
#' @importFrom stringr str_detect
#' @importFrom stringr str_extract
#' @importFrom stringr str_remove
#' @importFrom stringr str_remove_all
#' @importFrom stringr str_replace
#' @importFrom stringr str_replace_all
#' @importFrom stringr str_to_sentence
#' @importFrom tibble as_tibble
#' @importFrom tibble column_to_rownames
#' @importFrom tibble deframe
#' @importFrom tibble enframe
#' @importFrom tibble tibble
#' @importFrom tidyr complete
#' @importFrom tidyr expand_grid
#' @importFrom tidyr nesting
#' @importFrom tidyr pivot_longer
#' @importFrom tidyr pivot_wider
#' @importFrom tidyr unite
#' @importFrom tidyr unnest
#' @importFrom tidyselect matches
#' @importFrom tidyselect where
#' @importFrom utils head
## usethis namespace: end
NULL
