name: Build & CI Tests

on:
  push:
    branches: ["main", "dev"]
    tags:
      - "v*.*.*"
  pull_request:
    branches: ["main", "dev"]
  release:
    types: [published]
  workflow_dispatch:

permissions:
  id-token: write
  actions: write
  contents: read
  packages: write

jobs:
  build-and-push-container:
    name: Build Docker Image & Run CI Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up build environment
        id: setup_build_env
        uses: ./.github/actions/setup-image-build-env
        with:
          quay-username: ${{ secrets.QUAY_IO_USERNAME }}
          quay-password: ${{ secrets.QUAY_IO_PASSWORD }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/pixelgentechnologies/pixelatores
            890888997283.dkr.ecr.eu-north-1.amazonaws.com/experiment-summary
            quay.io/pixelgen-technologies/pixelatores
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha

      # Build base image and push
      - name: Build and push base Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          target: build
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            GITHUB_PAT=${{ secrets.GH_PAT }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # Build test image locally only
      - name: Build test image (local only)
        run: |
          docker build \
            --target test \
            --build-arg GITHUB_PAT=${{ secrets.GH_PAT }} \
            -t experiment-summary-test:${{ steps.meta.outputs.version }} .

      # Run CI tests inside local test image
      - name: Run R CMD check & Quarto smoke test
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/workspace \
            -w /workspace \
            experiment-summary-test:${{ steps.meta.outputs.version }} \
            /bin/bash -c "\
              quarto render inst/quarto/pixelatorES.qmd \
                -P sample_sheet='../../tests/testdata/es_test_data/es_test_data_samplesheet.csv' \
                -P data_folder='../../tests/testdata/es_test_data/' \
                -P debug_mode=TRUE \
                -P test_mode=TRUE \
                --output testrun.html"

